import random

def escolha_palavra() -> list:
    #lista de palavras
    tema = int(input("Qual tema você deseja?(1.Animais, 2.Frutas, 3.Paises, 4.Pokemon, 5.Steven Universe ou 6.Geral)"))
    #selecionando uma palavra aleatoria da lista que el selecionou
    if tema == 1:
        lista = ["PATO", "PERU", "BODE", "FOCA", "GATO", "ORCA", "RATO", "TATU", "SAGUI", "PANDA", "PAVAO", "POMBO" /
"PORCO", "ARARA", "CORVO", "FURAO", "GRILO", "MORSA", "URUBU", "ALPACA", "BAIACU", "BELUGA", "COIOTE", "CAMELO" /
"CORUJA", "CHACAL", "GIRAFA", "IGUANA", "JAVALI", "LONTRA", "LEMURE", "MACACO", "OURIÇO", "RAPOSA", "TUCANO", "BABUINO" /
"AXOLOTE", "CALANGO", "CANGURU", "CARACOL", "CEGONHA", "ESQUILO", "FORMIGA", "GALINHA", "HAMSTER", "JUMENTO", "LACRAIA", "MARMOTA" /
"MINHOCA", "PINGUIM", "PIRANHA"]
        palavra = random.choice(lista)
        palavra = palavra.strip()
    if tema == 2:
        lista = ["ABACATE", "ABACAXI", "ACEROLA", "AMORA", "BANANA", "CACAU", "CAJA", "CAQUI", "CARAMBOLA", "CEREJA", "FIGO", "FRAMBOESA" /
"GOIABA", "GROSELHA", "JABUTICABA", "JAMBO", "JENIPAPO", "KIWI", "LARANJA", "LIMAO", "MAMAO", "MANGA", "MARACUJA", "MELANCIA" /
"MORANGO", "PEQUI", "PESSEGO", "PITANGA", "PITAYA", "SIRIGUELA", "TAMARA", "TAMARINDO", "UVA"]
        palavra = random.choice(lista)
        palavra = palavra.strip()
    if tema == 3:
        lista = [
"ANGOLA", "EGITO", "MARROCOS", "ETIOPIA", "SOMALIA", "NIGER", "UGANDA", "NAMIBIA", "CAMAROES", "LIBERIA", "CONGO", "ZIMBABUE" /
"MADAGASCAR", "SENEGAL", "COLOMBIA", "ARGENTINA", "HAITI", "BAHAMAS", "CUBA", "HONDURAS", "JAMAICA", "MEXICO", "SURINAME", "BOLIVIA" /
"EQUADOR", "BRASIL", "PANAMA", "URURGUAI", "CANADA", "GRANADA", "PARAGUAI", "VENEZUELA", "CHILE", "GUATEMALA", "PERU", "AFEGANISTÃO" /
"JORDANIA", "SIRIA", "LAOS", "FILIPINAS", "LIBANO", "MALASIA", "TAILANDIA", "INDIA", "INDONESIA", "TURQUIA", "MONGOLIA", "NEPAL" /
"CHINA", "JAPAO", "PAQUISTAO", "AUSTRALIA", "TUVALU", "SAMOA", "DINAMARCA", "ITALIA", "ALEMANHA", "LIECHTENSTEIN", "ESPANHA", "LITUANIA" /
"AUSTRIA", "LUXEMBURGO", "ROMENIA", "RUSSIA", "MALTA", "BELGICA", "SERVIA", "GRECIA", "SUECIA", "HUNGRIA", "IRLANDA", "UCRANIA", "ISLANDIA"]
        palavra = random.choice(lista)
        palavra = palavra.strip()
    if tema == 4:
        lista = ["BULBASAUR", "IVYSAUR", "VENUSAUR", "CHARMANDER", "CHARMELEON", "CHARIZARD", "SQUIRTLE", "WARTORTLE", "BLASTOISE", "CATERPIE", "METAPOD", "BUTTERFREE" /
"WEEDLE", "KAKUNA", "BEEDRIL", "PIDGEY", "PIDGEOTTO", "PIDGEOT", "RATTATA", "RATICATE", "SPEAROW", "FEAROW", "EKANS", "ARBOK" /
"PIKACHU", "RAICHU", "SANDSHREW", "SANDSLASH", "NIDORAN", "NIDORINA", "NIDOQUEEN", "NIDORINO", "NIDOKING", "CLEFAIRY", "CLEFABLE", "VULPIX" /
"NINETALES", "JIGGLYPUFF", "WIGGLYTUFF", "ZUBAT", "GOLBAT", "ODDISH", "GLOOM", "VILEPLUME", "PARAS", "PARASECT", "VENONAT", "VENOMOTH" /
"DIGLETT", "DUGTRIO", "MEOWTH", "PERSIAN", "PSYDUCK", "GOLDUCK", "MANKEY", "PRIMEAPE", "GROWLITHE", "ARCANINE", "POLIWAG", "POLIWHIRL" /
"POLIWRATH", "ABRA", "KADABRA", "ALAKAZAM", "MACHOP", "MACHOKE", "MACHAMP", "BELLSPROUT", "WEEPINBELL", "VICTREEBEL", "TENTACOOL", "TENTACRUEL" /
"GEODUDE", "GRAVELER", "GOLEM", "PONYTA", "RAPIDASH", "SLOWPOKE", "SLOWBRO", "MEGNEMITE", "MAGNETON", "DODUO", "DODRIO", "SEEL" /
"DEWGONG", "GRIMER", "MUK", "SHELLDER", "CLOYSTER", "GASTLY", "HAUNTER", "GENGAR", "ONIX", "DROWZEE", "HYPNO", "KRABBY" /
"KINGLER", "VOLTORB", "ELECTRODE", "EXEGGUTE", "EXEGGUTOR", "CUBONE", "MAROWAK", "HITMONLEE", "HITMONCHAN", "LICKITUNG", "KOFFING", "WEEZING" /
"RHYHORN", "RHYDON", "CHANSEY", "TANGELA", "KANGASKHAN", "HORSEA", "SEADRA", "GOLDEEN", "SEAKING", "STARYU", "STARMIE", "SCYTHER" /
"JYNX", "ELECTABUZZ", "MAGMAR", "PINSIR", "TAUROS", "MAGIKARP", "GYARADOS", "LAPRAS", "DITTO", "EEVEE", "VAPOREON", "JOLTEON" /
"FLAREON", "PORYGON", "OMANYTE", "OMASTAR", "KABUTO", "KABUTOPS", "AERODACTYL", "SNORLAX", "ARTICUNO", "ZAPDOS", "MOLTRES", "DRATINI" /
"DRAGONAIR", "DRAGONITE", "MEWTWO", "MEW"]
        palavra = random.choice(lista)
        palavra = palavra.strip()
    if tema == 5:
        lista = ["AMETISTA", "PEROLA", "GARNET", "RUBI", "SAFIRA", "TOPAZIO", "QUARTZO", "DIAMANTE", "AQUAMARINE", "BLUEBIRD", "SUNSTONE", "FUME" /
"LAPIS", "JASPER", "CENTIPODA", "FLUORITA", "RODONITA", "OBSIDIANA", "ALEXANDRITA", "BISMUTO", "MALAQUITA", "PERIDOT", "AGATHA", "SARDONYX" /
"STEVEN", "GREG", "CONNIE", "STEVONNIE", "CEBOLA", "LARS", "SADIE", "RONALDO", "BUCKY"]
        palavra = random.choice(lista)
        palavra = palavra.strip()
    if tema == 6:
        lista = ["PATO", "PERU", "BODE", "FOCA", "GATO", "ORCA", "RATO", "TATU", "SAGUI", "PANDA" /
"PAVAO", "POMBO", "PORCO", "ARARA", "CORVO", "FURAO", "GRILO", "MORSA", "URUBU", "ALPACA" /
"BAIACU", "BELUGA", "COIOTE", "CAMELO", "CORUJA", "CHACAL", "GIRAFA", "IGUANA", "JAVALI", "LONTRA" /
"LEMURE", "MACACO", "OURIÇO", "RAPOSA", "TUCANO", "BABUINO", "AXOLOTE", "CALANGO", "CANGURU", "CARACOL" /
"CEGONHA", "ESQUILO", "FORMIGA", "GALINHA", "HAMSTER", "JUMENTO", "LACRAIA", "MARMOTA", "MINHOCA", "PINGUIM" /
"PIRANHA", "ABACATE", "ABACAXI", "ACEROLA", "AMORA", "BANANA", "CACAU", "CAJA", "CAQUI", "CARAMBOLA" /
"CEREJA", "FIGO", "FRAMBOESA", "GOIABA", "GROSELHA", "JABUTICABA", "JAMBO", "JENIPAPO", "KIWI", "LARANJA" /
"LIMAO", "MAMAO", "MANGA", "MARACUJA", "MELANCIA", "MORANGO", "PEQUI", "PESSEGO", "PITANGA", "PITAYA" /
"SIRIGUELA", "TAMARA", "TAMARINDO", "UVA", "ANGOLA", "EGITO", "MARROCOS", "ETIOPIA", "SOMALIA", "NIGER" /
"UGANDA", "NAMIBIA", "CAMAROES", "LIBERIA", "CONGO", "ZIMBABUE", "MADAGASCAR", "SENEGAL", "COLOMBIA", "ARGENTINA" /
"HAITI", "BAHAMAS", "CUBA", "HONDURAS", "JAMAICA", "MEXICO", "SURINAME", "BOLIVIA", "EQUADOR", "BRASIL" /
"PANAMA", "URURGUAI", "CANADA", "GRANADA", "PARAGUAI", "VENEZUELA", "CHILE", "GUATEMALA", "PERU", "AFEGANISTÃO" /
"JORDANIA", "SIRIA", "LAOS", "FILIPINAS", "LIBANO", "MALASIA", "TAILANDIA", "INDIA", "INDONESIA", "TURQUIA" /
"MONGOLIA", "NEPAL", "CHINA", "JAPAO", "PAQUISTAO", "AUSTRALIA", "TUVALU", "SAMOA", "DINAMARCA", "ITALIA" /
"ALEMANHA", "LIECHTENSTEIN", "ESPANHA", "LITUANIA", "AUSTRIA", "LUXEMBURGO", "ROMENIA", "RUSSIA", "MALTA", "BELGICA" /
"SERVIA", "GRECIA", "SUECIA", "HUNGRIA", "IRLANDA", "UCRANIA", "ISLANDIA", "BULBASAUR", "IVYSAUR", "VENUSAUR" /
"CHARMANDER", "CHARMELEON", "CHARIZARD", "SQUIRTLE", "WARTORTLE", "BLASTOISE", "CATERPIE", "METAPOD", "BUTTERFREE", "WEEDLE" /
"KAKUNA", "BEEDRIL", "PIDGEY", "PIDGEOTTO", "PIDGEOT", "RATTATA", "RATICATE", "SPEAROW", "FEAROW", "EKANS" /
"ARBOK", "PIKACHU", "RAICHU", "SANDSHREW", "SANDSLASH", "NIDORAN", "NIDORINA", "NIDOQUEEN", "NIDORINO", "NIDOKING" /
"CLEFAIRY", "CLEFABLE", "VULPIX", "NINETALES", "JIGGLYPUFF", "WIGGLYTUFF", "ZUBAT", "GOLBAT", "ODDISH", "GLOOM" /
"VILEPLUME", "PARAS", "PARASECT", "VENONAT", "VENOMOTH", "DIGLETT", "DUGTRIO", "MEOWTH", "PERSIAN", "PSYDUCK" /
"GOLDUCK", "MANKEY", "PRIMEAPE", "GROWLITHE", "ARCANINE", "POLIWAG", "POLIWHIRL", "POLIWRATH", "ABRA", "KADABRA" /
"ALAKAZAM", "MACHOP", "MACHOKE", "MACHAMP", "BELLSPROUT", "WEEPINBELL", "VICTREEBEL", "TENTACOOL", "TENTACRUEL", "GEODUDE" /
"GRAVELER", "GOLEM", "PONYTA", "RAPIDASH", "SLOWPOKE", "SLOWBRO", "MEGNEMITE", "MAGNETON", "DODUO", "DODRIO" /
"SEEL", "DEWGONG", "GRIMER", "MUK", "SHELLDER", "CLOYSTER", "GASTLY", "HAUNTER", "GENGAR", "ONIX" /
"DROWZEE", "HYPNO", "KRABBY", "KINGLER", "VOLTORB", "ELECTRODE", "EXEGGUTE", "EXEGGUTOR", "CUBONE", "MAROWAK", "HITMONLEE", "HITMONCHAN" /
"LICKITUNG", "KOFFING", "WEEZING", "RHYHORN", "RHYDON", "CHANSEY", "TANGELA", "KANGASKHAN", "HORSEA", "SEADRA" /
"GOLDEEN", "SEAKING", "STARYU", "STARMIE", "SCYTHER", "JYNX", "ELECTABUZZ", "MAGMAR", "PINSIR", "TAUROS" /
"MAGIKARP", "GYARADOS", "LAPRAS", "DITTO", "EEVEE", "VAPOREON", "JOLTEON", "FLAREON", "PORYGON", "OMANYTE" /
"OMASTAR", "KABUTO", "KABUTOPS", "AERODACTYL", "SNORLAX", "ARTICUNO", "ZAPDOS", "MOLTRES", "DRATINI", "DRAGONAIR" /
"DRAGONITE", "MEWTWO", "MEW", "AMETISTA", "PEROLA", "GARNET", "RUBI", "SAFIRA", "TOPAZIO", "QUARTZO" /
"DIAMANTE", "AQUAMARINE", "BLUEBIRD", "SUNSTONE", "FUME", "LAPIS", "JASPER", "CENTIPODA", "FLUORITA", "RODONITA" /
"OBSIDIANA", "ALEXANDRITA", "BISMUTO", "MALAQUITA", "PERIDOT", "AGATHA", "SARDONYX", "STEVEN", "GREG", "CONNIE" /
"STEVONNIE", "CEBOLA", "LARS", "SADIE", "RONALDO", "BUCKY"]
        palavra = random.choice(lista)
        palavra = palavra.strip()
    return palavra

def mascara(palavra:str) -> list:
    qnt = len(palavra)
    letras = []
    for x in range(qnt):
        letras.append("_")
    return letras

def verificacao_mascara(palavra:str, chute:str, letras:str):
        y=0
        passar = 0
        #verificando onde esta a letra na palavra
        for x in palavra:
            if chute == x:
                #mudando a letra na lista
                letras[y] = chute
                #verificando se tem outra em outro lugar
                if passar == 5:
                    break
                passar+=1
            y+=1
        return letras

def verificacao_vitoria(letras:str) -> bool:
    if "_" not in letras:
        print()
        print("você ganhou")
        return True
    return False